CREATE OR REPLACE STAGE RETAIL_STAGE;

-- run local using snowsql

-- PUT FILE:LOCAL-FILE-PATH @<DB-NAME>.<SCHEMA-NAME>.<STAGE-NAME>/STAGE-NAME/AUTOCOMPRESS=FALSE;

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Dimension_Tables/Dim_Loyalty_Program.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_LOYALTY_INFO/ 
      AUTO_COMPRESS=FALSE; #Snowflake will automatically compress files

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Dimension_Tables/Dim_Customer_Table.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_CUSTOMER/ 
      AUTO_COMPRESS=FALSE;

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Dimension_Tables/Dim_Date_Table.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_DATE/ 
      AUTO_COMPRESS=FALSE;

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Dimension_Tables/Dim_Product_Table.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_PRODUCT/ 
      AUTO_COMPRESS=FALSE;

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Dimension_Tables/Dim_Store_Table.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_STORE/ 
      AUTO_COMPRESS=FALSE;

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Fact_Table/Fact_Orders_Table.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/FACT_ORDERS/ 
      AUTO_COMPRESS=FALSE;

-- for bulk files

PUT 'file://C:/Users/anand/Projects/DS_Projects/Snow_Retail_Analytics_DWBI_Suite/Datasets/Bulk_Stores_Data/*.csv' @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/BULK_STORES_DATA/ 
      AUTO_COMPRESS=FALSE;

-- load data from stage to db tables

-- for Loyalty_Info Table
COPY INTO DIM_LOYALTY_INFO FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_LOYALTY_INFO/Dim_Loyalty_Program.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

-- for Dim_Customer Table
COPY INTO DIM_CUSTOMER (FIRST_NAME, LAST_NAME, GENDER, DOB, EMAIL, PHONE_NUMBER, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, LOYALTY_PROGRAM_ID)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_CUSTOMER/Dim_Customer_Table.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

-- for Dim_Date Table
COPY INTO DIM_DATE (DATE_ID, DATE, DAY_OF_WEEK, MONTH, QUARTER, YEAR, ISWEEKEND)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_DATE/Dim_Date_Table.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

-- for Dim_Product Table
COPY INTO DIM_PRODUCT (PRODUCT_NAME, CATEGORY, BRAND, UNIT_PRICE)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_PRODUCT/Dim_Product_Table.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

-- for Dim_Store Table
COPY INTO DIM_STORE (STORE_NAME, STORE_TYPE, STORE_OPENING_DATE, ADDRESS, CITY, STATE, COUNTRY, REGION, MANAGER_NAME)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/DIM_STORE/Dim_Store_Table.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

-- for Fact_Orders Table
COPY INTO FACT_ORDERS (CUSTOMER_ID, STORE_ID, ORDER_DATE_ID, PRODUCT_ID, QUANTITY_ORDERED, ORDER_AMOUNT, DISCOUNT_AMOUNT, 
                       SHIPPING_COST, TOTAL_AMOUNT)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/FACT_ORDERS/Fact_Orders_Table.csv 
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');


-- load Bulk Orders data
COPY INTO FACT_ORDERS (CUSTOMER_ID, STORE_ID, ORDER_DATE_ID, PRODUCT_ID, QUANTITY_ORDERED, ORDER_AMOUNT, DISCOUNT_AMOUNT, 
                       SHIPPING_COST, TOTAL_AMOUNT)
FROM @SNOW_RETAIL_DB.SNOW_RETAIL_SCHEMA.RETAIL_STAGE/BULK_STORES_DATA/
FILE_FORMAT = (FORMAT_NAME = 'CSV_SOURCE_FILE_FORMAT');

